### ISSUE TITLE
No ::pinv() function

### ISSUE THREAD

**Issue by pietrzakmat** [kirillv/cpp-inverse-kinematics-library#2]
It seems that in new Eigen library there is no ::pinv() function anymore. Perhaps it needs to be replaced with ::solve() function.

**Comment by kirillv** [comment]
Its a pseudo inverse. You can find it here http://eigen.tuxfamily.org/index.php?title=FAQ at the bottom - pinv

**Comment by pietrzakmat** [comment]
Yes, you are right. It just does not exists as integral part of Eigen lib. Closing.
