### ISSUE TITLE
“CCyclicCoordinateDescent.cpp”: No such file or directory

### ISSUE THREAD

**Issue by nixwang** [kirillv/cpp-inverse-kinematics-library#4]
Hello,
there is no "CCyclicCoordinateDescent.cpp” in directory,how can I add CCD Solver?thank you

**Comment by kirillv** [comment]
unfortunately iv lost original source code. ill try to find it in a few days. but no promises =) anyway it is rather simple to implement it.

**Comment by nixwang** [comment]
thanks a lot

**Comment by gordonwwang** [comment]
Excuse me, did you solve this problem? I also encountered it

**Comment by ollp** [comment]
seems not been solved any one please
